### ISSUE TITLE
Binderised version

### ISSUE THREAD

**Issue by psychemedia** [akloster/blender-vraag#1]
I notice that there is a [demo video](https://www.youtube.com/watch?v=0fRXGKq7yB4) showing how to script Blender from a Jupyter notebook notebook.

I wonder if it would be possible to demo this using a pre-built virtual machine? e.g. I did some doodles here https://github.com/psychemedia/ou-robotics-vrep/tree/master/robotVM connecting notebooks to the VREP robot simulator using a vagrant configured VM. On my to do list is to try to run the desktop in a Docker container using novnc, then maybe see if I can get it running in MyBinder (eg using https://github.com/jupyterhub/nbserverproxy to proxy the novnc desktop).

**Comment by akloster** [comment]
I don't quite understand what you are trying to achieve there. But first of all, the notebook server, the kernel process and the browser session showing the notebook don't need to be on the same (virtual/physical) machine, as long as they communicate on the network.

The work on using blender as a jupyter kernel is contained in my blender-asyncio project. I think the kernel code is already there, but I haven't written up the installation procedure yet.

**Comment by psychemedia** [comment]
In the demo? How to drive the simulator from a notebook, as well as how to pull eg video streams from the simulator into the notebook, with everything packaged in a VM so eg a student doesn't have to install/set-up anything other than running the VM.

In terms of Binderising blender, I was wondering if it'd be possible to provide a 'run on binder' demo showing how to control Blender (installed in the Binderised container) from a notebook.

**Comment by akloster** [comment]
You would have to implement the Jupyter kernel API in the simulator and then connect the notebook server to the kernel sockets exposed by the simulator. The "kernels" are separate processes, and there are kernels implemented in R and many other languages. In the case with Blender, it's the blender-asyncio project which implements a kernel inside a blender instance. Then the notebook server starts blender with that script and connects to the exposed Zeromq ports.

You can read up on how Jupyter works in their documentation.
